[supervisord]
nodaemon=true
user=root

[program:vncserver]
command=/usr/bin/env USER=root HOME=/root vncserver :1 -geometry 1920x1080 -depth 24
user=root
autorestart=unexpected
exitcodes=0
startsecs=2

[program:novnc]
command=websockify --web /usr/share/novnc/ 6080 localhost:5901
user=root
autorestart=true
