[supervisord]
nodaemon=true
user=root

[program:vncserver]
command=/usr/bin/vncserver :1 -fg -geometry 1920x1080 -depth 24
user=root
autorestart=true

[program:novnc]
command=websockify --web /usr/share/novnc/ 6080 localhost:5901
user=root
autorestart=true
